In [2]:
# Wikipedia Gauss-Newton Example, using very efficient scipy implementation

from scipy.optimize import curve_fit
import numpy as np
import matplotlib.pyplot as plt
from time import time
from numpy.linalg import solve
from numpy.linalg import pinv

In [61]:
# fun = [x+sin(y), y+sin(x)], so Jacobian = [[1,cos(y)],[cos(x),1]]

def test_fun(X):
    return np.array([X[0]+np.sin(X[1]), X[1]+np.sin(X[0])])

def test_jacobian(X):
    return np.array([[1,np.cos(X[1])],[np.cos(X[0]),1]])

In [81]:
X = np.array([-2.,1.])
step = 0.1

In [82]:
test_fun(X)

array([-1.15852902,  0.09070257])

In [83]:
test_jacobian(X)

array([[ 1.        ,  0.54030231],
       [-0.41614684,  1.        ]])

In [84]:
test_fun(X+np.ones(X.shape)*step)

array([-1.00879264,  0.15369991])

In [85]:
test_fun(X) + step*test_jacobian(X) @ test_fun(X)

array([-1.26948124,  0.14798465])

In [86]:
test_jacobian(X)

array([[ 1.        ,  0.54030231],
       [-0.41614684,  1.        ]])

In [87]:
np.linalg.det(test_jacobian(X))

1.224845095366153

In [102]:
b0 = np.array([-2,1])
b = b0 + 0.1

In [103]:
def compute_jacobian(b, b0, predict):
    '''
    '''
    b = b.astype(float)
    b0 = b0.astype(float)
    J = np.zeros((len(b),len(b)))
    for i in range(J.shape[1]):
        test_β = b0.copy()
        test_β[i] = b[i]
        delta = predict(test_β) - predict(b0)
        J[:,i] = delta / (b[i] - b0[i])
    Jt = J.T
    JtJ = Jt @ J
    return J

In [104]:
compute_jacobian(b,b0,test_fun)

array([[ 1.        ,  0.49736375],
       [-0.37002661,  1.        ]])